apiVersion: v1
kind: Secret
metadata:
  name: redis-cluster-1704204873
  namespace: default
  uid: 16f675e6-3221-419c-9e35-7aa79d2cd85b
  resourceVersion: '76568'
  creationTimestamp: '2024-01-02T14:14:34Z'
  labels:
    app.kubernetes.io/instance: redis-cluster-1704204873
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/version: 7.2.3
    helm.sh/chart: redis-cluster-9.1.4
  annotations:
    meta.helm.sh/release-name: redis-cluster-1704204873
    meta.helm.sh/release-namespace: default
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2024-01-02T14:14:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:redis-password: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:type: {}
  selfLink: /api/v1/namespaces/default/secrets/redis-cluster-1704204873
data:
  redis-password: dGprWmppeU9vSg==
type: Opaque
